name: Construir imagen Docker

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write

jobs:
  construir-imagen-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Iniciar sesión en GHCR con GITHUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Construir imagen Docker del backend
        run: docker build --no-cache --progress=plain \
          -t ghcr.io/instituto-politecnico-modelo/backend---uavdocx/backend-app:pr-${{ github.event.pull_request.number }} .

      - name: Subir imagen Docker a GHCR
        run: docker push ghcr.io/instituto-politecnico-modelo/backend---uavdocx/backend-app:pr-${{ github.event.pull_request.number }}
